services:
  - type: web
    name: podcast-summarizer
    env: python
    plan: free
    buildCommand: |
      bash build.sh
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application